#!/usr/bin/env python3
"""
gen_pci_table.py — converts a pci.ids file into a compact C header
(pci_table.h) containing a sorted array of {vendorId, deviceId, name}
entries plus a binary_search-friendly key, so quickfetch can resolve a
GPU's vendor:device pair in O(log n) with zero file I/O at runtime,
instead of linearly scanning a 2-3 MB text file on every cold lookup.

This mirrors what fastfetch does: pci.ids parsing happens once, at
build time, not on every invocation.

Usage:
    python3 gen_pci_table.py /usr/share/hwdata/pci.ids pci_table.h

If no path is given, it tries the usual system locations.
"""
import sys

DEFAULT_PATHS = [
    "/usr/share/hwdata/pci.ids",
    "/usr/share/misc/pci.ids",
    "/usr/share/pci.ids",
]


def parse(path):
    """Yields (vendor_id:int, device_id:int, name:str) for every device
    line in a pci.ids file. Vendor-only lines are skipped — we only need
    device-level names, matching what lookupPciNames() actually uses."""
    vendor_id = None
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        for raw in f:
            line = raw.rstrip("\n")
            if not line or line.startswith("#"):
                continue
            if line.startswith("\t\t"):
                continue  # subvendor/subdevice lines — not needed
            if line.startswith("C "):
                break  # class section starts — device data is done
            if line[0] != "\t":
                # top-level vendor line: "<hex id>  <name>"
                parts = line.split(None, 1)
                if len(parts) == 2:
                    try:
                        vendor_id = int(parts[0], 16)
                    except ValueError:
                        vendor_id = None
                else:
                    vendor_id = None
                continue
            if line[0] == "\t" and vendor_id is not None:
                parts = line[1:].split(None, 1)
                if len(parts) == 2:
                    try:
                        device_id = int(parts[0], 16)
                    except ValueError:
                        continue
                    name = parts[1].strip()
                    yield (vendor_id, device_id, name)


def escape(s):
    s = s.replace("\\", "\\\\").replace('"', '\\"')
    # \? is a valid C escape for '?' and reads identically at runtime,
    # but it prevents any "??X" sequence from ever being parsed as a
    # trigraph by a compiler/flags that honor them.
    s = s.replace("?", "\\?")
    return s


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else None
    out_path = sys.argv[2] if len(sys.argv) > 2 else "pci_table.h"

    if path is None:
        for candidate in DEFAULT_PATHS:
            try:
                open(candidate).close()
                path = candidate
                break
            except OSError:
                pass
        if path is None:
            print("No pci.ids found. Pass a path explicitly, e.g.:", file=sys.stderr)
            print("  python3 gen_pci_table.py /usr/share/hwdata/pci.ids", file=sys.stderr)
            sys.exit(1)

    entries = list(parse(path))
    # sorted by the same 32-bit key the binary search in C will use:
    # (vendorId << 16) | deviceId
    entries.sort(key=lambda e: (e[0], e[1]))

    with open(out_path, "w", encoding="utf-8") as out:
        out.write("/* Auto-generated by gen_pci_table.py from %s — do not edit by hand. */\n" % path)
        out.write("#ifndef QUICKFETCH_PCI_TABLE_H\n#define QUICKFETCH_PCI_TABLE_H\n\n")
        out.write("#include <stdint.h>\n\n")
        out.write("typedef struct {\n    uint32_t key;   /* (vendorId << 16) | deviceId */\n    const char *name;\n} PciEntry;\n\n")
        out.write("static const PciEntry pciTable[] = {\n")
        for vendor_id, device_id, name in entries:
            key = (vendor_id << 16) | device_id
            out.write('    { 0x%08Xu, "%s" },\n' % (key, escape(name)))
        out.write("};\n\n")
        out.write("#define PCI_TABLE_COUNT (sizeof(pciTable) / sizeof(pciTable[0]))\n\n")
        out.write("#endif\n")

    print("Wrote %d entries to %s" % (len(entries), out_path))


if __name__ == "__main__":
    main()
